apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: dterraform.azurecr.io/app3/python-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: dterraform-secret
# To schedule pods on based on NodeSelectors
      nodeSelector:
        app: system-apps
# service type ClusterIP       
---
apiVersion: v1
kind: Service
metadata:
  name: learn-devops-clusterip-service
  labels:
    app: python-app
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
    - port: 8080
      targetPort: 8080
 # Ingress
---      
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ssl
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
    
spec:
  rules:
  - host: wassupafrica.com
    http:
      paths:
      - path: /python-app
        backend:
          serviceName: learn-devops-clusterip-service
          servicePort: 8080
  tls:
  - hosts:
    - wassupafrica.com
    secretName: wassupafrica-secret  
    
    
--- 
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: oyedemilade@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
