apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: dterraform.azurecr.io/app3/python-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      imagePullSecrets:   # Update Image Pull Secret Name we creted
        - name: dterraform-secret
# To schedule pods on based on NodeSelectors
      nodeSelector:
        app: system-apps
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-svc
spec:
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
